# Resources/config/assets.yml
assets:

    wbw.jquery_datatables.asset.jquery_datatables:
        version: "1.13.8"
        themes:
            - "datatables"
            - "bootstrap"
            - "bootstrap4"
            - "bootstrap5"
            - "bulma"
            - "foundation"
            - "jqueryui"
            - "semanticui"
        requires:
            jszip:
                version: "3.10.1"
                stylesheets:
                javascripts:
                    - "/datatables-jszip-{{ version }}/jszip.min.js"
            pdfmake:
                version: "0.2.7"
                stylesheets:
                javascripts:
                    - "/datatables-pdfmake-{{ version }}/pdfmake.min.js"
                    - "/datatables-pdfmake-{{ version }}/vfs_fonts.js"
        plugins:
            autofill:
                version: "2.6.0"
                stylesheets:
                    - "/datatables-autofill-{{ version }}/css/autoFill.{{ theme }}.min.css"
                javascripts:
                    - "/datatables-autofill-{{ version }}/js/dataTables.autoFill.min.js"
                    - "/datatables-autofill-{{ version }}/js/autoFill.{{ theme }}.min.js"
            buttons:
                version: "2.4.2"
                stylesheets:
                    - "/datatables-buttons-{{ version }}/css/buttons.{{ theme }}.min.css"
                javascripts:
                    - "/datatables-buttons-{{ version }}/js/dataTables.buttons.min.js"
                    - "/datatables-buttons-{{ version }}/js/buttons.colVis.min.js"
                    - "/datatables-buttons-{{ version }}/js/buttons.flash.min.js"
                    - "/datatables-buttons-{{ version }}/js/buttons.html5.min.js"
                    - "/datatables-buttons-{{ version }}/js/buttons.print.min.js"
                    - "/datatables-buttons-{{ version }}/js/buttons.{{ theme }}.min.js"
            colreorder:
                version: "1.7.0"
                stylesheets:
                    - "/datatables-colreorder-{{ version }}/css/colReorder.{{ theme }}.min.css"
                javascripts:
                    - "/datatables-colreorder-{{ version }}/js/dataTables.colReorder.min.js"
            datetime:
                version: "1.5.1"
                stylesheets:
                    - "/datatables-datetime-{{ version }}/css/dataTables.dateTime.min.css"
                javascripts:
                    - "/datatables-datetime-{{ version }}/js/dataTables.dateTime.min.js"
            fixedcolumns:
                version: "4.3.0"
                stylesheets:
                    - "/datatables-fixedcolumns-{{ version }}/css/fixedColumns.{{ theme }}.min.css"
                javascripts:
                    - "/datatables-fixedcolumns-{{ version }}/js/dataTables.fixedColumns.min.js"
            fixedheader:
                version: "3.4.0"
                stylesheets:
                    - "/datatables-fixedheader-{{ version }}/css/fixedHeader.{{ theme }}.min.css"
                javascripts:
                    - "/datatables-fixedheader-{{ version }}/js/dataTables.fixedHeader.min.js"
            keytable:
                version: "2.11.0"
                stylesheets:
                    - "/datatables-keytable-{{ version }}/css/keyTable.{{ theme }}.min.css"
                javascripts:
                    - "/datatables-keytable-{{ version }}/js/dataTables.keyTable.min.js"
            responsive:
                version: "2.5.0"
                stylesheets:
                    - "/datatables-responsive-{{ version }}/css/responsive.{{ theme }}.min.css"
                javascripts:
                    - "/datatables-responsive-{{ version }}/js/dataTables.responsive.min.js"
                    - "/datatables-responsive-{{ version }}/js/responsive.{{ theme }}.min.js"
            rowgroup:
                version: "1.4.1"
                stylesheets:
                    - "/datatables-rowgroup-{{ version }}/css/rowGroup.{{ theme }}.min.css"
                javascripts:
                    - "/datatables-rowgroup-{{ version }}/js/dataTables.rowGroup.min.js"
            rowreorder:
                version: "1.4.1"
                stylesheets:
                    - "/datatables-rowreorder-{{ version }}/css/rowReorder.{{ theme }}.min.css"
                javascripts:
                    - "/datatables-rowreorder-{{ version }}/js/dataTables.rowReorder.min.js"
            scroller:
                version: "2.3.0"
                stylesheets:
                    - "/datatables-scroller-{{ version }}/css/scroller.{{ theme }}.min.css"
                javascripts:
                    - "/datatables-scroller-{{ version }}/js/dataTables.scroller.min.js"
            searchbuilder:
                version: "1.6.0"
                stylesheets:
                    - "/datatables-searchbuilder-{{ version }}/css/searchBuilder.{{ theme }}.min.css"
                javascripts:
                    - "/datatables-searchbuilder-{{ version }}/js/dataTables.searchBuilder.min.js"
                    - "/datatables-searchbuilder-{{ version }}/js/searchBuilder.{{ theme }}.min.js"
            searchpanes:
                version: "2.2.0"
                stylesheets:
                    - "/datatables-searchpanes-{{ version }}/css/searchPanes.{{ theme }}.min.css"
                javascripts:
                    - "/datatables-searchpanes-{{ version }}/js/dataTables.searchPanes.min.js"
                    - "/datatables-searchpanes-{{ version }}/js/searchPanes.{{ theme }}.min.js"
            select:
                version: "1.7.0"
                stylesheets:
                    - "/datatables-select-{{ version }}/css/select.{{ theme }}.min.css"
                javascripts:
                    - "/datatables-select-{{ version }}/js/dataTables.select.min.js"
            staterestore:
                version: "1.3.0"
                stylesheets:
                    - "/datatables-staterestore-{{ version }}/css/stateRestore.{{ theme }}.min.css"
                javascripts:
                    - "/datatables-staterestore-{{ version }}/js/dataTables.stateRestore.min.js"
                    - "/datatables-stateRestore-{{ version }}/js/stateRestore.{{ theme }}.min.js"

            editabletable:
                version: ""
                stylesheets:
                javascripts:
                    - "/editable-table/mindmup-editabletable.js"
