# Resources/config/assets.yml
assets:

    wbw.jquery_datatables.asset.jquery_datatables:
        version: "1.10.20"
        themes:
            - "bootstrap"
            - "bootstrap4"
            - "datatables"
            - "foundation"
            - "jqueryui"
            - "semanticui"
        requires:
            jszip:
                version: "2.5.0"
                javascripts:
                    - "/datatables-jszip-{{ version }}/jszip.min.js"
                stylesheets: []
            pdfmake:
                version: "0.1.36"
                javascripts:
                    - "/datatables-pdfmake-{{ version }}/pdfmake.min.js"
                    - "/datatables-pdfmake-{{ version }}/vfs_fonts.js"
                stylesheets: []
        plugins:
            autofill:
                version: "2.3.4"
                javascripts:
                    - "/datatables-autofill-{{ version }}/js/dataTables.autoFill.min.js"
                    - "/datatables-autofill-{{ version }}/js/autoFill.{{ theme }}.min.js"
                stylesheets:
                    - "/datatables-autofill-{{ version }}/css/autoFill.{{ theme }}.min.css"
            buttons:
                version: "1.6.0"
                javascripts:
                    - "/datatables-buttons-{{ version }}/js/dataTables.buttons.min.js"
                    - "/datatables-buttons-{{ version }}/js/buttons.colVis.min.js"
                    - "/datatables-buttons-{{ version }}/js/buttons.flash.min.js"
                    - "/datatables-buttons-{{ version }}/js/buttons.html5.min.js"
                    - "/datatables-buttons-{{ version }}/js/buttons.print.min.js"
                    - "/datatables-buttons-{{ version }}/js/buttons.{{ theme }}.min.js"
                stylesheets:
                    - "/datatables-buttons-{{ version }}/css/buttons.{{ theme }}.min.css"
            colreorder:
                version: "1.5.2"
                javascripts:
                    - "/datatables-colreorder-{{ version }}/js/dataTables.colReorder.min.js"
                stylesheets:
                    - "/datatables-colreorder-{{ version }}/css/colReorder.{{ theme }}.min.css"
            fixedcolumns:
                version: "3.3.0"
                javascripts:
                    - "/datatables-fixedcolumns-{{ version }}/js/dataTables.fixedColumns.min.js"
                stylesheets:
                    - "/datatables-fixedcolumns-{{ version }}/css/fixedColumns.{{ theme }}.min.css"
            fixedheader:
                version: "3.1.6"
                javascripts:
                    - "/datatables-fixedheader-{{ version }}/js/dataTables.fixedHeader.min.js"
                stylesheets:
                    - "/datatables-fixedheader-{{ version }}/css/fixedHeader.{{ theme }}.min.css"
            keytable:
                version: "2.5.1"
                javascripts:
                    - "/datatables-keytable-{{ version }}/js/dataTables.keyTable.min.js"
                stylesheets:
                    - "/datatables-keytable-{{ version }}/css/keyTable.{{ theme }}.min.css"
            responsive:
                version: "2.2.3"
                javascripts:
                    - "/datatables-responsive-{{ version }}/js/dataTables.responsive.min.js"
                    - "/datatables-responsive-{{ version }}/js/responsive.{{ theme }}.min.js"
                stylesheets:
                    - "/datatables-responsive-{{ version }}/css/responsive.{{ theme }}.min.css"
            rowgroup:
                version: "1.1.1"
                javascripts:
                    - "/datatables-rowgroup-{{ version }}/js/dataTables.rowGroup.min.js"
                stylesheets:
                    - "/datatables-rowgroup-{{ version }}/css/rowGroup.{{ theme }}.min.css"
            rowreorder:
                version: "1.2.6"
                javascripts:
                    - "/datatables-rowreorder-{{ version }}/js/dataTables.rowReorder.min.js"
                stylesheets:
                    - "/datatables-rowreorder-{{ version }}/css/rowReorder.{{ theme }}.min.css"
            scroller:
                version: "2.0.1"
                javascripts:
                    - "/datatables-scroller-{{ version }}/js/dataTables.scroller.min.js"
                stylesheets:
                    - "/datatables-scroller-{{ version }}/css/scroller.{{ theme }}.min.css"
            select:
                version: "1.3.1"
                javascripts:
                    - "/datatables-select-{{ version }}/js/dataTables.select.min.js"
                stylesheets:
                    - "/datatables-select-{{ version }}/css/select.{{ theme }}.min.css"

            editabletable:
                version: ""
                javascripts:
                    - "/editable-table/mindmup-editabletable.js"
                stylesheets: []
