# Resources/config/controllers.yml
services:

    wbw.jquery.datatables.controller.datatables:
        class: WBW\Bundle\JQuery\DataTablesBundle\Controller\DataTablesController
        calls:
            - [ "setContainer", [ "@service_container" ] ]

    WBW\Bundle\JQuery\DataTablesBundle\Controller\DataTablesController:
        alias:  "wbw.jquery.datatables.controller.datatables"
        public: true
