# Resources/config/controllers.yml
services:

    WBW\Bundle\JQuery\DataTablesBundle\Controller\DataTablesController:
        alias: "wbw.jquery.datatables.controller.datatables"

    wbw.jquery.datatables.controller.datatables:
        class:  WBW\Bundle\JQuery\DataTablesBundle\Controller\DataTablesController
        public: true
        calls:
            - [ "setContainer", [ "@service_container" ] ]
