# Resources/config/managers.yml
services:

    wbw.jquery.datatables.manager:
        class:  WBW\Bundle\JQuery\DataTablesBundle\Manager\DataTablesManager
        public: false
        arguments: [ "@logger" ]
