# src/Resources/config/assets.yml
assets:

    wbw.datatables.assets:
        version: "1.13.8"
        themes:
            - "datatables"
            - "bootstrap"
            - "bootstrap4"
            - "bootstrap5"
            - "bulma"
            - "foundation"
            - "jqueryui"
            - "semanticui"
        requires:
            jszip:
                version: "3.10.1"
                stylesheets:
                javascripts:
                    - "/datatables-jszip-{{ version }}/jszip.min.js"
            pdfmake:
                version: "0.2.7"
                stylesheets:
                javascripts:
                    - "/datatables-pdfmake-{{ version }}/pdfmake.min.js"
                    - "/datatables-pdfmake-{{ version }}/vfs_fonts.js"
        plugins:
            autofill:
                version: "2.6.0"
                stylesheets:
                    - "/datatables-autofill-{{ version }}/css/autoFill.{{ theme }}.min.css"
                javascripts:
                    - "/datatables-autofill-{{ version }}/js/dataTables.autoFill.min.js"
                    - "/datatables-autofill-{{ version }}/js/autoFill.{{ theme }}.min.js"
            buttons:
                version: "2.4.2"
                stylesheets:
                    - "/datatables-buttons-{{ version }}/css/buttons.{{ theme }}.min.css"
                javascripts:
                    - "/datatables-buttons-{{ version }}/js/dataTables.buttons.min.js"
                    - "/datatables-buttons-{{ version }}/js/buttons.colVis.min.js"
                    - "/datatables-buttons-{{ version }}/js/buttons.flash.min.js"
                    - "/datatables-buttons-{{ version }}/js/buttons.html5.min.js"
                    - "/datatables-buttons-{{ version }}/js/buttons.print.min.js"
                    - "/datatables-buttons-{{ version }}/js/buttons.{{ theme }}.min.js"
            colreorder:
                version: "1.7.0"
                stylesheets:
                    - "/datatables-colreorder-{{ version }}/css/colReorder.{{ theme }}.min.css"
                javascripts:
                    - "/datatables-colreorder-{{ version }}/js/dataTables.colReorder.min.js"
            datetime:
                version: "1.5.1"
                stylesheets:
                    - "/datatables-datetime-{{ version }}/css/dataTables.dateTime.min.css"
                javascripts:
                    - "/datatables-datetime-{{ version }}/js/dataTables.dateTime.min.js"
            fixedcolumns:
                version: "4.3.0"
                stylesheets:
                    - "/datatables-fixedcolumns-{{ version }}/css/fixedColumns.{{ theme }}.min.css"
                javascripts:
                    - "/datatables-fixedcolumns-{{ version }}/js/dataTables.fixedColumns.min.js"
            fixedheader:
                version: "3.4.0"
                stylesheets:
                    - "/datatables-fixedheader-{{ version }}/css/fixedHeader.{{ theme }}.min.css"
                javascripts:
                    - "/datatables-fixedheader-{{ version }}/js/dataTables.fixedHeader.min.js"
            keytable:
                version: "2.11.0"
                stylesheets:
                    - "/datatables-keytable-{{ version }}/css/keyTable.{{ theme }}.min.css"
                javascripts:
                    - "/datatables-keytable-{{ version }}/js/dataTables.keyTable.min.js"
            responsive:
                version: "2.5.0"
                stylesheets:
                    - "/datatables-responsive-{{ version }}/css/responsive.{{ theme }}.min.css"
                javascripts:
                    - "/datatables-responsive-{{ version }}/js/dataTables.responsive.min.js"
                    - "/datatables-responsive-{{ version }}/js/responsive.{{ theme }}.min.js"
            rowgroup:
                version: "1.4.1"
                stylesheets:
                    - "/datatables-rowgroup-{{ version }}/css/rowGroup.{{ theme }}.min.css"
                javascripts:
                    - "/datatables-rowgroup-{{ version }}/js/dataTables.rowGroup.min.js"
            rowreorder:
                version: "1.4.1"
                stylesheets:
                    - "/datatables-rowreorder-{{ version }}/css/rowReorder.{{ theme }}.min.css"
                javascripts:
                    - "/datatables-rowreorder-{{ version }}/js/dataTables.rowReorder.min.js"
            scroller:
                version: "2.3.0"
                stylesheets:
                    - "/datatables-scroller-{{ version }}/css/scroller.{{ theme }}.min.css"
                javascripts:
                    - "/datatables-scroller-{{ version }}/js/dataTables.scroller.min.js"
            searchbuilder:
                version: "1.6.0"
                stylesheets:
                    - "/datatables-searchbuilder-{{ version }}/css/searchBuilder.{{ theme }}.min.css"
                javascripts:
                    - "/datatables-searchbuilder-{{ version }}/js/dataTables.searchBuilder.min.js"
                    - "/datatables-searchbuilder-{{ version }}/js/searchBuilder.{{ theme }}.min.js"
            searchpanes:
                version: "2.2.0"
                stylesheets:
                    - "/datatables-searchpanes-{{ version }}/css/searchPanes.{{ theme }}.min.css"
                javascripts:
                    - "/datatables-searchpanes-{{ version }}/js/dataTables.searchPanes.min.js"
                    - "/datatables-searchpanes-{{ version }}/js/searchPanes.{{ theme }}.min.js"
            select:
                version: "1.7.0"
                stylesheets:
                    - "/datatables-select-{{ version }}/css/select.{{ theme }}.min.css"
                javascripts:
                    - "/datatables-select-{{ version }}/js/dataTables.select.min.js"
            staterestore:
                version: "1.3.0"
                stylesheets:
                    - "/datatables-staterestore-{{ version }}/css/stateRestore.{{ theme }}.min.css"
                javascripts:
                    - "/datatables-staterestore-{{ version }}/js/dataTables.stateRestore.min.js"
                    - "/datatables-stateRestore-{{ version }}/js/stateRestore.{{ theme }}.min.js"

            editabletable:
                version: ""
                stylesheets:
                javascripts:
                    - "/editable-table/mindmup-editabletable.js"

    wbw.bootstrap.assets:
        versions: { "3": "3.4.1", "4": "4.6.2", "5": "5.3.2" }
        plugins:
            bootstrap_colorpicker:
                version:     "2.5.3"
                description: "Bootstrap Colorpicker"
                stylesheets:
                    - "/bootstrap-colorpicker-{{ version }}/css/bootstrap-colorpicker.min.css"
                javascripts:
                    - "/bootstrap-colorpicker-{{ version }}/js/bootstrap-colorpicker.min.js"
            bootstrap_datepicker:
                version:     "1.9.0"
                description: "Bootstrap Datepicker"
                stylesheets:
                    - "/bootstrap-datepicker-{{ version }}/css/bootstrap-datepicker.min.css"
                javascripts:
                    - "/bootstrap-datepicker-{{ version }}/js/bootstrap-datepicker.min.js"
                    - "/bootstrap-datepicker-{{ version }}/locales/bootstrap-datepicker.{{ locale }}.min.js"
                locales:
                    - "ar"
                    - "ar-tn"
                    - "az"
                    - "bg"
                    - "bn"
                    - "br"
                    - "bs"
                    - "ca"
                    - "cs"
                    - "cy"
                    - "da"
                    - "de"
                    - "el"
                    - "en-AU"
                    - "en-GB"
                    - "en-IE"
                    - "en-NZ"
                    - "en-ZA"
                    - "eo"
                    - "es"
                    - "et"
                    - "eu"
                    - "fa"
                    - "fi"
                    - "fo"
                    - "fr-CH"
                    - "fr"
                    - "gl"
                    - "he"
                    - "hi"
                    - "hr"
                    - "hu"
                    - "hy"
                    - "id"
                    - "is"
                    - "it-CH"
                    - "it"
                    - "ja"
                    - "ka"
                    - "kh"
                    - "kk"
                    - "km"
                    - "ko"
                    - "kr"
                    - "lt"
                    - "lv"
                    - "me"
                    - "mk"
                    - "mn"
                    - "ms"
                    - "nb"
                    - "nl-BE"
                    - "nl"
                    - "no"
                    - "oc"
                    - "pl"
                    - "pt-BR"
                    - "pt"
                    - "ro"
                    - "rs-latin"
                    - "rs"
                    - "ru"
                    - "si"
                    - "sk"
                    - "sl"
                    - "sq"
                    - "sr-latin"
                    - "sr"
                    - "sv"
                    - "sw"
                    - "ta"
                    - "tg"
                    - "th"
                    - "tr"
                    - "uk"
                    - "uz-cyrl"
                    - "uz-latn"
                    - "vi"
                    - "zh-CN"
                    - "zh-TW"
            bootstrap_daterangepicker:
                version:     "2.1.27"
                description: "Bootstrap Daterangepicker"
                stylesheets:
                    - "/bootstrap-daterangepicker-{{ version }}/daterangepicker.css"
                javascripts:
                    - "/moment-2.20.1/moment-with-locales.min.js"
                    - "/bootstrap-daterangepicker-{{ version }}/daterangepicker.js"
            bootstrap_icons:
                version:     "1.11.0"
                description: "Bootstrap Icons"
                stylesheets:
                    - "/bootstrap-icons-{{ version }}/bootstrap-icons.css"
                javascripts: [ ]
            bootstrap_markdown:
                version:     "2.10.0"
                description: "Bootstrap Markdown"
                stylesheets:
                    - "/bootstrap-markdown-{{ version }}/css/bootstrap-markdown.min.css"
                javascripts:
                    - "/bootstrap-markdown-{{ version }}/js/bootstrap-markdown.js"
                    - "/bootstrap-markdown-{{ version }}/locale/bootstrap-markdown.{{ locale }}.js"
                locales:
                    - "ar"
                    - "cs"
                    - "da"
                    - "de"
                    - "es"
                    - "fa"
                    - "fr"
                    - "ja"
                    - "kr"
                    - "nb"
                    - "nl"
                    - "pl"
                    - "ru"
                    - "sl"
                    - "sv"
                    - "tr"
                    - "ua"
                    - "zh"
            bootstrap_notify:
                version:     "3.1.3"
                description: "Bootstrap Notify"
                stylesheets: [ ]
                javascripts:
                    - "/bootstrap-notify-{{ version }}/bootstrap-notify.min.js"
            bootstrap_select:
                version:     "1.12.4"
                description: "Bootstrap Select"
                stylesheets:
                    - "/bootstrap-select-{{ version }}/css/bootstrap-select.min.css"
                javascripts:
                    - "/bootstrap-select-{{ version }}/js/bootstrap-select.min.js"
                    - "/bootstrap-select-{{ version }}/js/i18n/defaults-{{ locale }}.min.js"
                locales:
                    - "ar_AR"
                    - "bg_BG"
                    - "cro_CRO"
                    - "cs_CZ"
                    - "da_DK"
                    - "de_DE"
                    - "en_US"
                    - "es_CL"
                    - "es_ES"
                    - "et_EE"
                    - "eu"
                    - "fa_IR"
                    - "fi_FI"
                    - "fr_FR"
                    - "hu_HU"
                    - "id_ID"
                    - "it_IT"
                    - "ja_JP"
                    - "kh_KM"
                    - "ko_KR"
                    - "lt_LT"
                    - "nb_NO"
                    - "nl_NL"
                    - "pl_PL"
                    - "pt_BR"
                    - "pt_PT"
                    - "ro_RO"
                    - "ru_RU"
                    - "sk_SK"
                    - "sl_SI"
                    - "sv_SE"
                    - "tr_TR"
                    - "ua_UA"
                    - "vi_VN"
                    - "zh_CN"
                    - "zh_TW"
            bootstrap_slider:
                version:     "10.0.0"
                description: "Bootstrap Slider"
                stylesheets: [ ]
                javascripts:
                    - "/bootstrap-slider-{{ version }}/bootstrap-slider.min.js"
            bootstrap_social:
                version:     "5.1.1"
                description: "Bootstrap Social"
                stylesheets:
                    - "/bootstrap-social-{{ version }}/bootstrap-social.css"
                javascripts:
            bootstrap_tagsinput:
                version:     "0.8.0"
                description: "Bootstrap Tagsinput"
                stylesheets:
                    - "/bootstrap-tagsinput-{{ version }}/bootstrap-tagsinput.css"
                javascripts:
                    - "/bootstrap-tagsinput-{{ version }}/bootstrap-tagsinput.min.js"
            bootstrap_timepicker:
                version:     "0.5.2"
                description: "Bootstrap Timepicker"
                stylesheets:
                    - "/bootstrap-timepicker-{{ version }}/css/bootstrap-timepicker.min.css"
                javascripts:
                    - "/bootstrap-timepicker-{{ version }}/js/bootstrap-timepicker.min.js"
            bootstrap_wysiwyg:
                version:     "0.3.3"
                description: "Bootstrap WYSIWYG"
                stylesheets:
                    - "/bootstrap-wysiwyg-{{ version }}/bootstrap3-wysihtml5.min.css"
                javascripts:
                    - "/wysihtml-0.4.15/wysihtml5x-toolbar.min.js"
                    - "/handlebars-1.3.0/handlebars.runtime.js"
                    - "/bootstrap-wysiwyg-{{ version }}/bootstrap3-wysihtml5.min.js"
                    - "/bootstrap-wysiwyg-{{ version }}/locales/bootstrap-wysihtml5.{{ locale }}.js"
                locales:
                    - "ar-AR"
                    - "bg-BG"
                    - "ca-CT"
                    - "cs-CZ"
                    - "da-DK"
                    - "de-DE"
                    - "el-GR"
                    - "en-US"
                    - "es-AR"
                    - "es-ES"
                    - "fr-FR"
                    - "hr-HR"
                    - "hu-HU"
                    - "il-HE"
                    - "it-IT"
                    - "ja-JP"
                    - "ko-KR"
                    - "lt-LT"
                    - "mo-MD"
                    - "nb-NB"
                    - "nl-NL"
                    - "pl-PL"
                    - "pt-BR"
                    - "ru-RU"
                    - "sk-SK"
                    - "sv-SE"
                    - "tr-TR"
                    - "ua-UA"
                    - "zh-CN"
                    - "zh-TW"
            summernote:
                version:     "0.8.20"
                description: "Summernote"
                bootstrap: { "3": "", "4": "-bs4" }
                stylesheets:
                    - "/summernote-{{ version }}/summernote{{ bootstrap }}.css"
                javascripts:
                    - "/summernote-{{ version }}/summernote.min.js"
                    - "/summernote-{{ version }}/lang/summernote-{{ locale }}.js"
                locales:
                    - "ar-AR"
                    - "bg-BG"
                    - "ca-ES"
                    - "cs-CZ"
                    - "da-DK"
                    - "de-DE"
                    - "el-GR"
                    - "es-ES"
                    - "es-EU"
                    - "fa-IR"
                    - "fi-FI"
                    - "fr-FR"
                    - "gl-ES"
                    - "he-IL"
                    - "hr-HR"
                    - "hu-HU"
                    - "id-ID"
                    - "it-IT"
                    - "ja-JP"
                    - "ko-KR"
                    - "lt-LT"
                    - "lt-LV"
                    - "mn-MN"
                    - "nb-NO"
                    - "nl-NL"
                    - "pl-PL"
                    - "pt-BR"
                    - "pt-PT"
                    - "ro-RO"
                    - "ru-RU"
                    - "sk-SK"
                    - "sl-SI"
                    - "sr-RS"
                    - "sr-RS-Latin"
                    - "sv-SE"
                    - "ta-IN"
                    - "th-TH"
                    - "tr-TR"
                    - "uk-UA"
                    - "uz-UZ"
                    - "vi-VN"
                    - "zh-CN"
                    - "zh-TW"
