# src/Resources/config/commands.yml
services:

    wbw.datatables.command.provider_list:
        class:  WBW\Bundle\DataTablesBundle\Command\DataTablesProviderListCommand
        public: false
        calls:
            - [ "setDataTablesManager", [ "@wbw.datatables.manager" ] ]
            - [ "setTranslator",        [ "@translator" ] ]
        tags:
            - { name: "console.command" }
