# Resources/config/controllers.yml
services:

    WBW\Bundle\DataTablesBundle\Controller\DataTablesController:
        alias:  "wbw.datatables.controller.datatables"
        public: true

    wbw.datatables.controller.datatables:
        class:  WBW\Bundle\DataTablesBundle\Controller\DataTablesController
        public: false
        calls:
            - [ "setContainer",         [ "@Psr\\Container\\ContainerInterface" ] ]
            - [ "setDataTablesManager", [ "@wbw.datatables.manager" ] ]
        tags:
            - { name: "container.service_subscriber" }
