# .github/workflows/analysis.yml
name: "Static analysis"

on: [ push ]

jobs:

    build:
        name:    "PHPStan"
        runs-on: ubuntu-22.04

        steps:
            -   name: "Checkout"
                uses: actions/checkout@v4

            -   name: "Setup"
                uses: shivammathur/setup-php@v2
                with:
                    php-version: "7.1"
                    coverage:    "xdebug"

            -   name: "Composer"
                run:  |
                      php --version
                      composer --version
                      COMPOSER_MEMORY_LIMIT=-1 composer update

            -   name: "PHPStan"
                run:  |
                      vendor/bin/phpstan --version
                      vendor/bin/phpstan analyse --error-format=github --configuration phpstan.conf.neon
